inherit_from:
  - .rubocop_system.yml
inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
  Exclude:
    - 'Guardfile'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/**/*'
Style/HashSyntax:
  EnforcedShorthandSyntax: either

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'next_page.gemspec'
    - 'gemfiles/*'
    - 'Rakefile'
    - 'lib/next_page/version.rb'
    - 'bin/test'
    - 'spec/dummy/bin/*'
    - 'spec/dummy/Rakefile'
    - 'spec/dummy/db/schema.rb'
