inherit_from:
  - .rubocop_system.yml
inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'Guardfile'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/**/*'

AllCops:
  TargetRubyVersion: 2.7.6
  NewCops: enable
  Exclude:
    - 'next_page.gemspec'
    - 'gemfiles/*'
    - 'Rakefile'
    - 'lib/next_page/version.rb'
    - 'bin/test'
    - 'spec/dummy/bin/*'
    - 'spec/dummy/Rakefile'
    - 'spec/dummy/db/schema.rb'
