# these are externally defined "system" files; rather than correct them, they are excluded here

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/app/controllers/application_controller.rb'
    - 'spec/dummy/app/jobs/application_job.rb'
    - 'spec/dummy/app/mailers/application_mailer.rb'
    - 'spec/dummy/app/models/application_record.rb'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/config/application.rb'
    - 'spec/dummy/config/boot.rb'
    - 'spec/dummy/config/environment.rb'
    - 'spec/dummy/config/environments/development.rb'
    - 'spec/dummy/config/environments/production.rb'
    - 'spec/dummy/config/environments/test.rb'
    - 'spec/dummy/config/initializers/application_controller_renderer.rb'
    - 'spec/dummy/config/initializers/backtrace_silencers.rb'
    - 'spec/dummy/config/initializers/cors.rb'
    - 'spec/dummy/config/initializers/filter_parameter_logging.rb'
    - 'spec/dummy/config/initializers/inflections.rb'
    - 'spec/dummy/config/initializers/mime_types.rb'
    - 'spec/dummy/config/initializers/wrap_parameters.rb'
    - 'spec/dummy/config/puma.rb'
    - 'spec/dummy/config/routes.rb'
    - 'spec/dummy/config/spring.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/dummy/app/controllers/application_controller.rb'
    - 'spec/dummy/app/mailers/application_mailer.rb'
    - 'spec/dummy/app/models/application_record.rb'
    - 'spec/dummy/config/application.rb'

Style/GlobalStdStream:
  Exclude:
    - 'spec/dummy/config/environments/production.rb'

Style/StringLiterals:
  Exclude:
    - 'spec/dummy/config/application.rb'
    - 'spec/dummy/config/puma.rb'
    - 'spec/dummy/config/spring.rb'
    - 'spec/rails_helper.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'spec/dummy/config/puma.rb'
