default: &default
  adapter: postgresql
  encoding: unicode
  user: next_page
  host: localhost
  password: GoBears!
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: next_page

test:
  <<: *default
  database: next_page_test
