version: '3'
services:
  db:
    container_name: next_page_db
    image: postgres:10.7
    environment:
      - POSTGRES_USER=next_page
      - POSTGRES_DB=next_page
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
