name: RuboCop
on:
  - push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install RuboCop
        run: |
          gem install bundler --no-document
          gem install rubocop -v 1.31.2 --no-document
      - name: RuboCop
        run: rubocop
